// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiyagMGbNOhuLmi2_oYd_lDGbC-N3E44E',
    appId: '1:494943227729:web:e6f34a2b0148cdf0b38d70',
    messagingSenderId: '494943227729',
    projectId: 'bunkmate-c8818',
    authDomain: 'bunkmate-c8818.firebaseapp.com',
    storageBucket: 'bunkmate-c8818.appspot.com',
    measurementId: 'G-67YQ8TDRKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_q8QDdhEUvgkUqOYDmPeDBXzAiCw-xhE',
    appId: '1:494943227729:android:2b73abe9c51bd69fb38d70',
    messagingSenderId: '494943227729',
    projectId: 'bunkmate-c8818',
    storageBucket: 'bunkmate-c8818.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzrUBj3PQ79yvygrYCn4o9iW7WkPrn-jM',
    appId: '1:494943227729:ios:fc2b8835ec1a69e3b38d70',
    messagingSenderId: '494943227729',
    projectId: 'bunkmate-c8818',
    storageBucket: 'bunkmate-c8818.appspot.com',
    iosClientId: '494943227729-afn2b4dahkk6lnneof848rk7e1vpfhj7.apps.googleusercontent.com',
    iosBundleId: 'dev.prateekthakur.bunkmate',
  );
}
